### ISSUE TITLE
Add more features to csvresults function

### ISSUE THREAD

**Issue by PavanTeja2005** [cro2003/rgpvApi#10]
Hi, I want to generalize the csvresults function to be able to read data from both csv and excel files
and as the csv reader function reads rows one by one, I want to make it fast such that it fetches multiple results in parallel. 

 I'm currently working on GSSoC Extended. Please assign me the labels.

@cro2003

**Comment by cro2003** [comment]
Sure, that's a great idea, before that can you elaborate how will you achieve parallel result fetching?

**Comment by PavanTeja2005** [comment]
I'm planning to use threads to make multiple requests and fetch data at once.

**Comment by cro2003** [comment]
That Works but remember rgpv can deny your requests so make sure to balance that out.

**Comment by PavanTeja2005** [comment]
Okay., thank you. I will make sure to keep that in check. 
And as the library uses pyteserract,  I'm planning to add a method to handle the case when the user's system doesn't contain the tesseract software and prompt them with the steps and details to install the software along with the proper  links to download the software based on their system.

**Comment by PavanTeja2005** [comment]
can you please provide me with test data

**Comment by cro2003** [comment]
Sure you can test with below info
Enollment Series: 0176CS221001 - 0176CS221200
Course Id: 24
Semester: 4

**Comment by PavanTeja2005** [comment]
Can you please check out my pull request..

**Comment by cro2003** [comment]
Sure will do.
