### ISSUE TITLE
✨adding dark mode✨

### ISSUE THREAD

**Issue by trahulprabhu38** [cro2003/rgpvApi#13]
@cro2003 if you could assign me this task , then i would love to implement dark mode features.

**Comment by cro2003** [comment]
I guess you are talking about the documentation, it is generated by sphinx. I will be more happy if you can add more feature in the core project.

**Comment by trahulprabhu38** [comment]
oh im not fully aware of sphinx , i can try once.

**Comment by cro2003** [comment]
No worries, dont worry about the UI-UX side as this is the python package so mostly users will care about the functionality of the code so I will be more happy if you can add more feature in the core project.

**Comment by trahulprabhu38** [comment]
is then any UI changes u would like .

**Comment by cro2003** [comment]
For now there's nothing.

**Comment by cro2003** [comment]
Closing this Issue for now!
