### ISSUE TITLE
improving ui

### ISSUE THREAD

**Issue by Aditijainnn** [cro2003/rgpvApi#14]
Making ui of this project 
assign this issue to me under gssoc ext and hacktoberfest

**Comment by cro2003** [comment]
I guess you are talking about the documentation, it is generated by sphinx. I will be more happy if you can add more feature in the core project.

**Comment by cro2003** [comment]
Closing this Issue for now, you can raise an issue again, if you would like to add feature in core project.

**Comment by Aditijainnn** [comment]
> Closing this Issue for now, you can raise an issue again, if you would like to add feature in core project.

ok sure
