### ISSUE TITLE
[ Level1 Enhancement ] #Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [cro2003/rgpvApi#16]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by cro2003** [comment]
Currently we are not interested in this feature it would be great if you can contribute in the core project.

**Comment by cro2003** [comment]
Closing this Issue for now, you can Raise new Issue again
