### ISSUE TITLE
[feature enhancemement] : Enhance the UI

### ISSUE THREAD

**Issue by snehaapratap** [cro2003/rgpvApi#21]
![image](https://github.com/user-attachments/assets/30152071-84f4-4772-b801-532f32c95163)
The UI of a page can make a page more dynamic and interactive.
Please assign me this task as i can enhance the UI as well as make changes in the footer.
Thank you!

**Comment by cro2003** [comment]
It is the Documentation which is Generated by Sphinx so there's no need for updation in UI/UX Side. I will be more happy if you can add more feature in the core project.
