### ISSUE TITLE
no follow us section at the website

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [cro2003/rgpvApi#22]
no follow us section at the website
<img width="959" alt="image" src="https://github.com/user-attachments/assets/2f995b55-c32d-41b7-b6d8-c06aa9f460ae">

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
assign this task to me

**Comment by cro2003** [comment]
It is the Documentation which is Generated by Sphinx so there's no need for updation in UI/UX Side. I will be more happy if you can add more feature in the core project.
