### ISSUE TITLE
Security Enhancement

### ISSUE THREAD

**Issue by BondadaSusanthi** [cro2003/rgpvApi#25]
Description:

I want to enhance the security of the result class used for fetching examination results from the RGPV website. 

Current Concerns:

Potential exposure of sensitive user information during data retrieval.
Insufficient validation and sanitization of inputs, which could lead to vulnerabilities.
Lack of encryption for data in transit.

Proposed Enhancements:

Implementing HTTPS for secure data transmission.
Adding input validation and sanitization to prevent injection attacks.
Using secure cookies and token-based authentication for session management.

**Comment by BondadaSusanthi** [comment]
I'm GSSOC Contributor, I want to contribute to this website by enhancing security. Looking forward to it

**Comment by cro2003** [comment]
It's a python packages. It would be great if you can add more features in the project itself.

**Comment by BondadaSusanthi** [comment]
Hi,I've checked the website, I found few issues
1) In the faculty database section, I can't find the information of faculty
2)Since it's rgpv college website, in the faculty database section under the institute only rgpv clg name should be shown, but it is showing all the institutions
3)picture gallery section is giving 404 error

Can you assign me , I will work on it

**Comment by cro2003** [comment]
1. There's no function in our package to get Faculty Information
2. Same there's no Function for Faculty
3. There's also no picture gallery in our package

**Comment by cro2003** [comment]
Closing this issue for now you can create a new one again
