### ISSUE TITLE
Proposal fpr GitHub bot to acknowledge issues

### ISSUE THREAD

**Issue by Abhi9shinde** [cro2003/rgpvApi#26]
Description:
I propose creating a GitHub bot that automatically responds to new issues with a message thanking users for their contributions and informing them that our team will review it shortly.
When raised a issue I saw there was no bot to respond to the issues.
So I would like to work on it

Benefits:
Enhances user experience by providing immediate feedback.
Encourages more contributions to our project.

Please assign this task to me under hacotoberfest, gssoc-ext

**Comment by cro2003** [comment]
For now we are not interested in this, it would be great if you can add feature in the core project.
