### ISSUE TITLE
UI Enhancement Proposal

### ISSUE THREAD

**Issue by neeru24** [cro2003/rgpvApi#27]
I'd like to propose changes to the website's UI to make it more visually appealing and user-friendly. The current design can be improved to create a better experience, with enhancements like:

- Modernizing the layout for a cleaner look.
- Improving color schemes and typography for better readability.
- Adding subtle animations for smoother navigation.

This will make the site more engaging and improve the overall user experience. Looking forward to getting assigned! 😊

![image](https://github.com/user-attachments/assets/9382ff6e-82d6-49d0-9cb1-058d8feef370)

**Comment by cro2003** [comment]
It's a documentation which is generated by Sphinx so there's no need for the UI Updation. I will be more happy if you can contribute to the core project

**Comment by cro2003** [comment]
Closing this issue for now you can create a new one again

**Comment by neeru24** [comment]
> Closing this issue for now you can create a new one again

Okay, Can I raise an another issue for the readme updation. It can be updated with addition of contrubutor pics, table showing number of forks, prs, stars etc

**Comment by cro2003** [comment]
Currently we are only Accepting Issues / enhancement in our Core Project, so it would be great if you can contribute in that.
