### ISSUE TITLE
Adding Asynchronous Support

### ISSUE THREAD

**Issue by MrinmayiVerma** [cro2003/rgpvApi#3]
thsi website barely gives the viewer any idea about what it is. nor this it give any info regarding what is available. the choice of colours and navigation, everything can be more attractive and easier to use

**Comment by smog-root** [comment]
i can help you with that!. To transform the website into a more engaging, informative, and user-friendly platform that effectively communicates its purpose and offerings.

i'm currently work on GSSoc24 can you add labels of gssoc and level3 for it. and assign this me!!?

@MrinmayiVerma @cro2003

**Comment by cro2003** [comment]
It is the Documentation which is Generated by Sphinx so there's no need for updation in UI/UX Side. I will be more happy if you can add more feature in the python module.

**Comment by smog-root** [comment]
Okay! I can add more modules!! Assign me!!

Add a label of gssoc-extd and level3! (It's a request!)

**Comment by cro2003** [comment]
Sure, what feature would you like to add, you can checkout https://rgpv.ac.in/

**Comment by smog-root** [comment]
1. Concurrency

Module: asyncio (or) concurrent.

Purpose: To allow fetching multiple results concurrently, which can speed up processing if you're dealing with multiple.

Usage: Use asynchronous requests or threads to make parallel API calls.

**Comment by smog-root** [comment]
2.
Module: logging

Purpose: To capture and record logs for debugging and monitoring the application's behavior.

Usage: Replace print statements or silent failures with appropriate logging calls to capture information on execution flow, errors, and warnings.

**Comment by smog-root** [comment]
i need a enrollment ID and a course ID. to test?!

**Comment by cro2003** [comment]
Sure Here's a series of enrollment 0176CS221001 - 0176CS221200 & the Course is B.Tech. also please checkout `rgpvApi.info_api.info.courseId()` , Also I have assigned you for this Feature 1. Also Please Elaborate the 2nd Feature

**Comment by smog-root** [comment]
i finish it by 1 week or so.. i will update to you!

Discord: the_p1r4te

contact me!!

**Comment by cro2003** [comment]
Sure you can contact me on cro2003
