### ISSUE TITLE
Adding Caching 

### ISSUE THREAD

**Issue by anishka25** [cro2003/rgpvApi#32]
Cache certain API responses to reduce API requests (e.g., student information, course catalog, common results).

(I want to work on this issue)

**Comment by cro2003** [comment]
It's a Good Idea. Could you elaborate how will you add this feature?

**Comment by anishka25** [comment]
So I can do it based upon 2 strategies , first one includes the use of redis database and the other one includes using SQlite in memory database which will use caching headers to store and reuse frequently requested data, reducing server load and API calls.

so whatever you want , i can use that approach to implement it!

**Comment by cro2003** [comment]
Currently this Project is also Python Package as well, and currently its not hosted on any server, Anyone can download the package from pypi and use it. So if we include Redis or sqlite then we have to create the API endpoints and host it on server.

**Comment by anishka25** [comment]
We can cache the results on disk instead of hosting on server

**Comment by cro2003** [comment]
Sure go ahead.
