### ISSUE TITLE
Adding Exception Handling to python files

### ISSUE THREAD

**Issue by Sai-ganesh-0004** [cro2003/rgpvApi#34]
**Description**
Implement structured exception handling across all Python files in the project. The goal is to improve the robustness of the code by catching and handling errors gracefully, providing meaningful error messages, and logging critical failures.

**Key Areas**

- Global Error Handler: Add a global error handler to catch unhandled exceptions.
- Specific Exception Handling: Implement specific exception handling for external API calls, file operations, and database connections.
- Logging: Ensure all exceptions are logged with appropriate severity levels for easier debugging.
- User-Friendly Messages: Provide clear, user-friendly error messages to avoid exposing technical details.

**Comment by Sai-ganesh-0004** [comment]
I want to Work on this issue under gssoc-ext

**Comment by cro2003** [comment]
Which types of Error we are considering here?

**Comment by Sai-ganesh-0004** [comment]
there can be requests.ConnectionError or parsing and beautifulSoup Errors

**Comment by cro2003** [comment]
Its a python package as well so it will be used by Developer so they can identify these error, like Connection Error is when we are offline and beutifulSoup will only give error if rgpv is down
