### ISSUE TITLE
Adding contributing.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [cro2003/rgpvApi#35]
Without contributing.md files contributors didn't understand how to contribute and which process they should follow.

I want to add the following points -
Project Overview
How to Contribute
Contribution Guidelines
Opening a Pull Request
Issue Report Process
Technologies Used
Community and Communication
Project Structure
Inspiration for Contributions

Also , I will try to make ik more creative.
If any further changes required please tell me.

**Comment by cro2003** [comment]
Currently we are not considering any updation to readme or UI/UX changes, it would be great if you can contribute to the core project.
