### ISSUE TITLE
 Update README.md and Add CONTRIBUTING.md Files

### ISSUE THREAD

**Issue by anchalchaturvedi08** [cro2003/rgpvApi#36]
We need to enhance the documentation of our project to improve clarity and encourage contributions from the community. This task involves two main activities:

1. Update README.md:
   - Add detailed setup and installation instructions.
   - Provide a clear overview of the project, its purpose, and its features.
   - Include usage examples and any relevant screenshots or diagrams.
   - Update contact information and links to relevant resources.

2. Add CONTRIBUTING.md:
   - Create a CONTRIBUTING.md file to guide new contributors.
   - Outline the process for submitting issues and pull requests.
   - Include guidelines for code style, testing, and committing changes.
   - Provide information on how contributors can get in touch for further assistance.

These updates will help ensure that our documentation is comprehensive and user-friendly, making it easier for new users and contributors to understand and participate in the project.

**Comment by cro2003** [comment]
Currently we are Interested in these Features, it would be great if you can contribute in the core project.
