### ISSUE TITLE
Add GitHub Repository Stats to README.md &  Gssoc fest logo 

### ISSUE THREAD

**Issue by noobrehan18** [cro2003/rgpvApi#38]
🔴 Enhancement Aim : This enhancement will make the repository more user-friendly by providing visibility into its overall activity.
🔴 Changes :

The issue involves adding a table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions in the repository at a glance.
Steps to Implement:

1-Create a table in the README.md file displaying the following repository statistics:
Stars
Forks
Open Issues
Open Pull Requests
Closed Pull Requests
2-

Use markdown syntax to include badges or icons for each statistic, along with dynamic links to the corresponding sections of the repository.
Expected Behavior:
The README.md file will contain a neatly formatted table that displays real-time repository statistics, making the repository's activity more visible and engaging for contributors and users.
Additional Information:
This enhancement will make the repository more user-friendly by providing visibility into its overall activity.
The table can be dynamically updated by using GitHub shields or other badge services to fetch real-time stats.

<img width="844" alt="Screenshot 2024-10-22 at 6 15 34 PM" src="https://github.com/user-attachments/assets/1dfc2d1e-90db-410e-9f66-8a3151f7088f">
 & update the readme with proper will enhance the repo pls assign me under gssoc level 2 label

**Comment by cro2003** [comment]
Currently we are Interested in these Features, it would be great if you can contribute in the core project.
