### ISSUE TITLE
Implement CSV Functionality for Fetching Examination Results

### ISSUE THREAD

**Issue by Himanshi-m** [cro2003/rgpvApi#4]
[Function Idea] Implementation of a function that allows users to fetch examination results in bulk using a CSV file containing enrollment IDs at once and receive their corresponding results in a structured CSV or JSON format.
Proposed Functionality:
Input CSV Format: The input CSV should contain a single column labeled enrolment_id with enrollment numbers of the students.
Output (for eg. if CSV Format):
The output CSV can include the following columns:
enrolment_id, name, status (e.g., PASS/FAIL/PASS WITH GRACE), sgpa ,cgpa, subjects (a formatted json of subjects with their respective grades), etc
Implementation Details:
Can use the existing methods from the rgpvApi.result to fetch results (getMain, getReval, getChlng) by allowing users to specify the type of results they wish to fetch (Main, Revaluation, Challenge) along with course ID and semester.
This functionality will provide a more streamlined and efficient way for users to access examination results for multiple students without needing to make individual requests. (especially for institutes willing to download results of all their students)
I would like to request to be assigned this issue, I am eager to contribute to this feature under gssoc-ext and hacktoberfest-accepted. Would love to have any suggestions or amendments in the idea from your side as well.

**Comment by cro2003** [comment]
Sure that's a great idea to fetch results of students in bulk, I have assigned you for this Feature and also added the labels.

**Comment by Himanshi-m** [comment]
Great. Working on it. It would be helpful to know if i should move with the output format as the formatted json of existing results like 
{"enrolment_id": {json of (getMain/getReval/getChlng) }, ... } ?

**Comment by cro2003** [comment]
Sure you can test with below info 
Enollment Series: 0176CS221001 - 0176CS221200
Course Id: 24
Semester: 4

**Comment by Himanshi-m** [comment]
Did checks already. I study in one of the institutes of rgpv so used those enrollment ids. You can check the pr :)

**Comment by Himanshi-m** [comment]
Hey, the label should be gssoc-ext not gssoc-extd please check and fix that.
