### ISSUE TITLE
Refactoring: Enhancement of the Documentation

### ISSUE THREAD

**Issue by VanshGarg06** [cro2003/rgpvApi#43]
**Problem Description**
The present documentation of the API is not that appealing and the user experience is not that good.

**Desktop**
OS : Windows 10 Home Single
Search Engine: Google Chrome
Version: 130.0.6723.70 (Official Build) (64-bit)

**Solution** 
The format of the document shown needs to be changed so as to increase the user experience and the documentation looks more appealing.

**Additional Context**
Name: @VanshGarg06
Please assign this issue to me @cro2003 under hacktoberfest and gssoc-ext under level 3 with necessary labels.
Please assign this issue as soon as possible, so that i could merge the pull request.

**Comment by cro2003** [comment]
Its created by Sphinx so there's no need of changes in it.
