### ISSUE TITLE
Upgradation: __init__.py is not needed 

### ISSUE THREAD

**Issue by VanshGarg06** [cro2003/rgpvApi#44]
**Problem Description**
The __init__.py file is not required and included unnecessary and any processing is not done with including the unnecessary files which increases the size.

**Desktop**
OS : Windows 10 Home Single
Search Engine: Google Chrome
Version: 130.0.6723.70 (Official Build) (64-bit)

**Solution**
The __init__.py will be removed as file or will be blank so that the size will be reduced.

**Additional Context**
Name: @VanshGarg06
Please @cro2003 assign this issue to me under the hacktoberfest and gssoc-ext under the level 2 with necessary labels.
Please assign this issue to me @cro2003  as soon as possible so that i am able to merge pull request.

**Comment by cro2003** [comment]
Its needed as its a Python Package .

**Comment by cro2003** [comment]
Closing this for now, you can create new Issue again.
