### ISSUE TITLE
Implement Notification System for Important Academic Dates

### ISSUE THREAD

**Issue by imDarshanGK** [cro2003/rgpvApi#49]
We are looking to enhance the functionality of the rgpvApi by implementing a Notification System that will keep students informed about important academic dates and deadlines. This feature will help students manage their schedules more effectively and reduce the risk of missing crucial information.

Objectives:
1} Develop a notification system to alert users about:
2} Upcoming exam dates
3} Assignment submission deadlines
4} Results announcements
5}  dates for new courses, Etc

Thank You,
@cro2003

**Comment by cro2003** [comment]
Its a package so notification system will not work as notification mainly used for notify which can be on web application or apps
