### ISSUE TITLE
Enhancement of whole UI and Addition of Code Snippet Copy Feature.

### ISSUE THREAD

**Issue by Shariq2003** [cro2003/rgpvApi#7]
1. I want to improve the UI and UX of main/landing page that refactors the user interactivity and provides a better experience for use.
2. I also want to put the code snippet in the code block that enhance the readability and also provides a copy feature.

![image](https://github.com/user-attachments/assets/f5e2efbd-7d54-4316-948d-c56ccc85ec80)

Overall UI and UX will improve.

@cro2003 please assign this issue to me under GsSoc Ext.

**Comment by cro2003** [comment]
It is the Documentation which is Generated by Sphinx so there's no need for updation in UI/UX Side. I will be more happy if you can add more feature in the core project.
