### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [cro2003/rgpvApi#8]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by cro2003** [comment]
Currently our Project isn't that Huge & it also doesn't have that much contributors. I will be more happy if you can add more feature in the core project.
