### ISSUE TITLE
Add more details in README.md filr ahout project.

### ISSUE THREAD

**Issue by SimranShaikh20** [cro2003/rgpvApi#9]
@cro2003 
Hi, I am Simran Shaikh. I’ve been reviewing the project as part of my contribution to GSSoC Extended 24 and noticed that  README.md do not contain more details description about this project . It only show basic details . My suggestion is to add more description what this project meaning and how to used it .
 I would like to work on this.
If you like this idea, please assign the task to me and add the corresponding charts to it.
Thank you for your time and consideration!
![image](https://github.com/user-attachments/assets/5a40643c-2a81-4f21-92ac-5ef1c7f88a41)

**Comment by cro2003** [comment]
Hey, We already have Documentation link in about section of the repo

**Comment by SimranShaikh20** [comment]
Yeah i had saw it but mostly people don't see files they prefer to see README.md file . Because when we open some repo we direct see README.md file then we will go through entire file .
I hope you had understand what i am trying to convey.
@cro2003

**Comment by cro2003** [comment]
Yeah but it is a python package and we have to upload the documentation on pypi & we use the format of the documentation which other packages does. I will be more happy if you can add more feature in the core project.

**Comment by SimranShaikh20** [comment]
Okay i will see where i can contribute for core project. And let know about it .

**Comment by cro2003** [comment]
Till that I am closing this one, you can Open again when you found one.
